---

- name: Playbook to setup desktop
  hosts: localhost
  gather_facts: false
  become: true
  tasks:
    - name: update apt 
      apt:
        upgrade: yes 
        update_cache: yes
    - name: install apt packages
      apt:
        pkg:
          - vim
          - vlc 
          - terminator
          - openconnect
          - gnome-tweaks
          - chromium-browser
          - goldendict
          - docker.io
          - docker-compose
          - wireguard
          # exfat-fuse, exfat-utils
    - name: isntall snap packages
      community.general.snap:
        name:
          - joplin-desktop
          - telegram-desktop
          #- onlyoffice-desktopeditors #huge enough to skip
    - name: isntall snap classic packages
      community.general.snap:
        name:
          - sublime-text
          - slack
        classic: yes
