---

- name: Playbook to setup desktop
  hosts: desktop
  gather_facts: false
  become: true
  tasks:
#gsettings set org.gnome.desktop.input-sources sources "[('xkb', 'us'), ('xkb', 'ru')]"
#gsettings set org.gnome.desktop.input-sources xkb-options "['grp:caps_toggle']"
#gsettings set org.gnome.desktop.interface gtk-theme 'Adwaita-dark'^V
    #- name: add ru layout
    #  community.general.dconf:
    #    key: "/org/gnome/desktop/input-sources/sources"
    #    value: "[('xkb', 'us'), ('xkb', 'ru')]"
    #- name: set layout switch to caps
    #  community.general.dconf:
    #    key: "/org/gnome/desktop/input-sources/xkb-options"
    #    value: "['grp:caps_toggle']"
    - name: enable dark theme
      community.general.dconf:
        key: "/org/gnome/desktop/interface/gtk-theme"
        value: 'Yaru-dark'
    - name: update apt 
      apt:
        upgrade: yes 
        update_cache: yes
    - name: install apt packages
      apt:
        pkg:
          - vim
          - vlc 
          - terminator
          - openconnect
          - gnome-tweaks
          - chromium-browser
          - goldendict
          - docker.io
          - docker-compose
          - wireguard
    - name: isntall snap packages
      community.general.snap:
        name:
          - joplin-desktop
          - telegram-desktop
          #- onlyoffice-desktopeditors #huge enough to skip
    - name: isntall snap classic packages
      community.general.snap:
        name:
          - sublime-text
          - slack
        classic: yes
