---

- name: gnome
  hosts: localhost
  gather_facts: false
  become: false
  tasks:
    - include: tasks/gnome.yml

- name: Playbook to setup desktop
  hosts: localhost # desktop
  gather_facts: false
  become: true
  tasks:
    - name: update apt 
      apt:
        upgrade: yes 
        update_cache: yes
    - name: install apt packages
      become: true
      apt:
        pkg:
          #- wget
          - htop
          - tmux
          - git
          - screen
          - curl
          - net-tools
          - gparted
          #- lshw-gtk
          #- vmfs-tools
          #- wine-stable
          #- steam-installer
          - network-manager-openconnect-gnome
          - vim
          - vlc 
          - terminator
          - openconnect
          - gnome-tweaks
          #- chromium-browser
          - goldendict
          - docker.io
          - docker-compose
          - wireguard
    - name: isntall snap packages
      community.general.snap:
        name:
          - joplin-desktop
          - telegram-desktop
          #- onlyoffice-desktopeditors #huge enough to skip
    - name: isntall snap classic packages
      community.general.snap:
        name:
          - sublime-text
          - slack
        classic: yes
    - name: add autostart applications
      vars:
        user: "{{ lookup('env','USER') }}" #remove
        apps:
          - subl
          - firefox
          #- chromium-browser
          - terminator
      template:
        src: "autostart.desktop.j2"
        dest: "/home/{{ user }}/.config/autostart/{{ item }}.desktop"
      with_items: "{{ apps }}"


#/etc/systemd/logind.conf
#[Login]
#HandleLidSwitch=ignore
