---

- name: Playbook to setup desktop
  hosts: target
  gather_facts: false
  become: true
  vars_files:
    - defaults/main.yml
  tasks:
    - name: update apt 
      apt:
        upgrade: yes 
        update_cache: yes
    - name: install apt packages
      become: true
      apt:
        pkg: "{{ apt_packages }}"
#    - name: isntall snap packages
#      community.general.snap:
#        name:
#          - joplin-desktop
#          - telegram-desktop
#          #- onlyoffice-desktopeditors #huge enough to skip
#    - name: isntall snap classic packages
#      community.general.snap:
#        name:
#          - sublime-text
#          - sublime-merge
#          - slack
#          #- pycharm-community
#        classic: yes
    - name: add autostart applications
      vars:
        user: "{{ lookup('env','USER') }}" #remove
        apps:
          #- subl
          #- firefox
          #- chromium-browser
          #- terminator
      template:
        src: "autostart.desktop.j2"
        dest: "/home/{{ user }}/.config/autostart/{{ item }}.desktop"
      with_items: "{{ apps }}"

# TODO: drop gnome-games, autoremove

- name: gnome
  hosts: target
  gather_facts: false
  become: false
  tasks:
    - include: tasks/gnome.yml

