- name: add ru layout
  community.general.dconf:
    key: "/org/gnome/desktop/input-sources/sources"
    value: "[('xkb', 'us'), ('xkb', 'ru')]"
- name: set layout switch to caps
  community.general.dconf:
    key: "/org/gnome/desktop/input-sources/xkb-options"
    value: "['grp:caps_toggle']"
- name: enable dark theme
  community.general.dconf:
    key: "/org/gnome/desktop/interface/gtk-theme"
    value: "'Yaru-dark'" # Single quotes inside fouble quotes
- name: dark theme (2)
  community.general.dconf:
    key: "/org/gnome/desktop/interface/color-scheme"
    value: "'prefer-dark'"
