alias wu='sudo wg-quick up /etc/wireguard/ruvdsp2.conf'
alias wd='sudo wg-quick down /etc/wireguard/ruvdsp2.conf'

alias v='source ~/osenv/bin/activate'
alias nenv='source /home/user/git/dynamic_inv/ansible2119/bin/activate'
alias got='git'
alias gits='git status'
alias gitd='git diff'
alias gitp='git pull'
alias gsl='git stash list'
alias g-1='git reset --hard HEAD~1'
alias ppid='ps -o ppid= -p'
alias gitorig="find . -name '*\.orig'"
alias git-fixup='git commit -a --fixup HEAD'
alias fix='git commit -a --fixup=HEAD'

alias valo='vault login --method=ldap username=$VAULT_USER'
alias ose='echo $OS_REGION_NAME'
alias r='echo $OS_REGION_NAME'

alias aptade='sudo apt-get update && sudo apt-get upgrade -y'
alias updade='sudo apt-get update && sudo apt-get upgrade -y'

alias tome='cd /home/user/Downloads/t-engine4-linux64-1.6.7; ./t-engine'
